### ISSUE TITLE
[BUG] Problem with indentation

### ISSUE THREAD

**Issue by brunonishimoto** [thu-coai/ConvLab-2#100]
**Describe the bug**
There is an indentation error at file `convlab2/policy/evaluate.py` on line `219`. The **`else`** statement should be nested inside the **`for`** loop, right? Aligned with the **`if`** statement.

![image](https://user-images.githubusercontent.com/18452584/92232374-d1bade80-ee84-11ea-8507-79c90a940355.png)

**Comment by truthless11** [comment]
No. The code is correct. It will execute the `else` clause only if the dialog exceeds the maximum dialog turns (40 here). You can refer to [Else Clauses on Loop Statements](https://book.pythontips.com/en/latest/for_-_else.html) for more details in Python.
