### ISSUE TITLE
[Feature] The user simulator always says something that is not clear

### ISSUE THREAD

**Issue by ShaneTian** [thu-coai/ConvLab-2#104]
**Describe the feature**
For the following goal:
```json
{
  "attraction": {
    "info": {
      "area": "west"
    },
    "reqt": {
      "entrance fee": "?",
      "phone": "?"
    }
  },
  "hotel": {
    "info": {
      "internet": "yes",
      "pricerange": "cheap",
      "type": "guesthouse"
    },
    "reqt": {
      "phone": "?"
    }
  },
  "taxi": {
    "info": {
      "arriveBy": "18:30"
    },
    "reqt": {
      "car type": "?",
      "phone": "?"
    }
  }
}
```

The user simulator said:
```
I ca n't wait to get there and see some of the local attractions . I am looking for a place to stay . Can you help me ? I also need a place to go in the west .
```

It is not clear for `area` slot value `west`

**Comment by zqwerty** [comment]
Template NLG generate a sentence for each slot-value. `I also need a place to go in the west .` comes from `[Inform, Restaurant, Area, west]`

**Comment by ShaneTian** [comment]
Thanks @zqwerty 
I mean, which one does `in the west` refer to in this sentence
- `I ca n't wait to get there and see some of the local attractions .`: attraction in the west?
- `I am looking for a place to stay .`: hotel in the west?

We can't just tell by this sentence `I also need a place to go in the west .`

**Comment by zqwerty** [comment]
This is the error of templateNLG, `I am looking for a place to stay .` is redundant. fixed
