### ISSUE TITLE
Result bias of DAMD model in Convlab-2 and original paper, and downloading problem

### ISSUE THREAD

**Issue by wxtyixiao** [thu-coai/ConvLab-2#11]
Excuse me, I just want to know why there exists big bias between the result of DAMD model in Convlab-2 and the original paper?
The success rate is 60.4% in original paper and 33.6% in ConvLab-2.

When i want to run the test files in tests directory, the downloading of pre-trained models always get errors although i have tried many times. Is there other method for downloading?

**Comment by truthless11** [comment]
@wxtyixiao This is because the original paper calculates the success rate at the turn level (60.4%), our ConvLab2 evaluates the model at the dialog level (33.6%), which involves multi-turn interactions.

**Comment by zqwerty** [comment]
you can download the data manually using google colab
