### ISSUE TITLE
[BUG] Task success on evaluator.py

### ISSUE THREAD

**Issue by brunonishimoto** [thu-coai/ConvLab-2#114]
**Describe the bug**
At file **`convlab2/policy/evaluate.py`**, on line `224` we need the code to be `task_success[key] = [task_succ]`, right?
The way it is now, we do not count the `task_succ` when `key`appears the first time.

![image](https://user-images.githubusercontent.com/18452584/93121701-a6619c00-f69b-11ea-97bd-25ec59e27a3f.png)

**Comment by zqwerty** [comment]
@truthless11 @liangrz15 please check this

**Comment by truthless11** [comment]
Done.
