### ISSUE TITLE
[BUG] 2 issue in Visualization Service Deployment

### ISSUE THREAD

**Issue by alznn** [thu-coai/ConvLab-2#123]
Thank you for making the tool!
however, while I was trying to deploy the toolbox, there are some problems:
1. while start Visualization Service and open the website, the program return 200 and shut down
2. in the visualization page, everything can't work like the demo video, the page seems empty
![tool_bug](https://user-images.githubusercontent.com/11405478/93865479-f6bea680-fcf8-11ea-8743-847250fed682.jpg)

**Comment by zqwerty** [comment]
Could you provide more information? Which config do you use?

**Comment by alznn** [comment]
Hi 
Thank you for your reply
I guess the config I used is MultiWOZ,
I was following the document:
1. clone the repository, 
2. install ConvLab-2 via pip
3. try the [Getting Started](https://github.com/thu-coai/ConvLab-2/blob/master/tutorials/Getting_Started.ipynb) page
4. skip [Add New Model](https://github.com/thu-coai/ConvLab-2/blob/master/tutorials/Add_New_Model.md) &[ Train RL Policies](https://github.com/thu-coai/ConvLab-2/tree/master/tutorials/Train_RL_Policies) part, cause I assume that there are default model can be used
5. run Visualization Service directly

and happen the problems mention in this issue

My environment is ubuntu14.04,and I used conda to build a virtual environment, everything is run in the virtual environment.

Hope the information can help!

**Comment by zqwerty** [comment]
Sorry, but I cannot reproduce in ubuntu 18.04 and convlab2 conda env. It seems that the connection has some problems. More detail information may help
