### ISSUE TITLE
evaluating error while training DST module in CrossWoz

### ISSUE THREAD

**Issue by alznn** [thu-coai/ConvLab-2#135]
https://github.com/thu-coai/ConvLab-2/blob/bbad3cb42fd711115ff15056150b43bd0d48d6a4/convlab2/dst/trade/crosswoz/models/TRADE.py#L238

while training DST module in crosswoz , in the evaluation phase will happen TypeError()  (shown as below)
![圖片](https://user-images.githubusercontent.com/11405478/94403863-a0da7a80-01a0-11eb-909a-90964963fc92.png)

after tracing the source code, the bug may  be caused by this line
I annotate the code  and the module train smoothly, but I still not sure is this the proper modify way

report this issue and hope it would help

**Comment by zz-jacob** [comment]
Your correction is right.
I update the code and delete this line.

**Comment by zqwerty** [comment]
Thanks!

**Comment by alznn** [comment]
Thanks a lot!
