### ISSUE TITLE
[BUG] CrossWOZ slot "name" from selectedResults should be string & \xa0 in slot values

### ISSUE THREAD

**Issue by adamlin120** [thu-coai/ConvLab-2#144]
**Describe the bug**

0d45aa65d4cae704972569a801a4375e42075f7f use selectedResults for missing name. 
However, selectedResults are List instead of String.

Also, I found that several slot values in crosswoz contain `\xa0`.

Changing this to 
`domain_state['name'] = selected_results[0]`
might resolve the first issue.

https://github.com/thu-coai/ConvLab-2/blob/732afebf4135452917ba8389575c9e35e30b9425/convlab2/dst/dstc9/utils.py#L48

Cleaning the return value with
`" ".join(unified_value.strip().split())`
might resolve the second one.

https://github.com/thu-coai/ConvLab-2/blob/732afebf4135452917ba8389575c9e35e30b9425/convlab2/dst/dstc9/utils.py#L65-L82

**To Reproduce**
Here is an example with above issues. 
_The first turn in the first dialogue when loading crosswoz-en test set using `prepare_data` form `from convlab2.dst.dstc9.utils`_

`{'Attraction': {'duration': '',
                'fee': '',
                'name': '',
                'nearby attract.': '',
                'nearby hotels': '',
                'nearby rest.': '',
                'rating': ''},
 'Hotel': {'Hotel Facilities': '',
           'name': '',
           'nearby attract.': '',
           'nearby hotels': '',
           'nearby rest.': '',
           'price': '',
           'rating': '',
           'type': ''},
 'Metro': {'from': '', 'to': ''},
 'Restaurant': {'cost': '50-100 yuan',
                'dishes': 'Food court',
                'name': ['Xianyukou\xa0Time-honored Food\xa0Street'],
                'nearby attract.': '',
                'nearby hotels': '',
                'nearby rest.': '',
                'rating': ''},
 'Taxi': {'from': '', 'to': ''}}`

**Comment by function2-llx** [comment]
Thank you for your suggestions!

In fact the first issue has already been covered [here](https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/dst/dstc9/utils.py#L120).

We will address the second issue ASAP.

**Comment by function2-llx** [comment]
We are going to address the second issue by cleaning both the label and prediction value during evaluation.

**Comment by adamlin120** [comment]
Awesome 👍 

Thank you!
