### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sherlock1987** [thu-coai/ConvLab-2#15]
**Describe the bug**
This platform could not train a MLE model.
When I load the MLE model for GDPL, PPO, PG, it could train with no problem, but it never gets to the optimal score(I run evluate.py to see the model). Actually it goes down after few eopchs. And here is a graph I made in GDPL, and PPO is pretty similar to this one.

**To Reproduce**
Simply run train.py in PG/GDPL/PPO, and it will give this issue. I write a script which could evluate all of the models in one dir, and here is the graph I made about GDPL.

**Expected behavior**
The evluate score should go higher when loaded MLE model.
Score for PPO:
 [0.52, 0.53, 0.54, 0.49, 0.44, 0.49, 0.46, 0.47, 0.44, 0.43, 0.42, 0.44, 0.47, 0.48, 0.49, 0.46, 0.45, 0.46, 0.45, 0.48, 0.46, 0.48, 0.49, 0.49, 0.49, 0.48, 0.45, 0.47, 0.43, 0.43, 0.43, 0.42, 0.42, 0.41, 0.42, 0.43, 0.44, 0.47, 0.45, 0.43]
So, the max of PPO is just goes to 0.53, not like 0.74.

**Comment by zqwerty** [comment]
Thanks! We will check it in a few days.

**Comment by zqwerty** [comment]
Please check if you re-install ConvLab-2 since the code has changed. (`pip install -e .` in ConvLab-2)

**Comment by sherlock1987** [comment]
Yeah, I have already change the code, sure about that.

**Comment by zqwerty** [comment]
I have tried these:
in mle/multiwoz/: python train.py
in ppo/: python train.py --load_path ../mle/multiwoz/save/best_mle
in policy/: python evaluate.py --model_name PPO --load_path ppo/save/9_ppo (I choose 9_ppo randomly)
and get:
```
All 100 0.73
reward: 11.143058441558441
```

**Comment by sherlock1987** [comment]
Oh, that is cool, for me the PPO is also good, but for GDPL, there are still some problem exists.

**Comment by LinZichuan** [comment]
> I have tried these:
> in mle/multiwoz/: python train.py
> in ppo/: python train.py --load_path ../mle/multiwoz/save/best_mle
> in policy/: python evaluate.py --model_name PPO --load_path ppo/save/9_ppo (I choose 9_ppo randomly)
> and get:
> 
> ```
> All 100 0.73
> reward: 11.143058441558441
> ```

Hi @zqwerty , Thanks for the tips. This works for the commit 2422980acd! 
But when I run these commands for the latest commit (c6372b1), I found the problem is still unsolved. The performance of PPO will still rise to 65% at the beginning and then start dropping at later training stage (to around 35%).
Could you help look into it? Thanks!

**Comment by zqwerty** [comment]
move to #54

**Comment by ShuoZhangXJTU** [comment]
> I have tried these:
> in mle/multiwoz/: python train.py
> in ppo/: python train.py --load_path ../mle/multiwoz/save/best_mle
> in policy/: python evaluate.py --model_name PPO --load_path ppo/save/9_ppo (I choose 9_ppo randomly)
> and get:
> 
> ```
> All 100 0.73
> reward: 11.143058441558441
> ```

Hey guys, I tested PPO on the latest version of convab-2 today and I got a success rate of 84% that is way bigger than the reported 73%, I wonder if there are any mistakes? If not, I think the performance record should be updated.
