### ISSUE TITLE
policy module：rule_simulator.py 中的 begin_da() function 導致同一輸入不同輸出

### ISSUE THREAD

**Issue by alznn** [thu-coai/ConvLab-2#159]
您好，在串 crosswoz 各 module 時，在 policy 部分遇到 DST 送入資料時，在 policy 的 begin_da() 中的  active_tuples_num = random.choices([2, 3, 4], [30, 50, 20])[0]，導致模型最後 output 不一致，以下為案例：
### case1
Input："您好，我想找一家评分是4.5分以上、做金牌烤鸭好吃的餐馆，有什么地方呀？顺便帮我看看几点营业？”
Output：你好，人均消费是1000元以上。
程式在 begin_da() 中的輸出:
![圖片](https://user-images.githubusercontent.com/11405478/98640917-da88ce80-2365-11eb-997f-aeb8423428ed.png)

### case2:
Input："您好，我想找一家评分是4.5分以上、做金牌烤鸭好吃的餐馆，有什么地方呀？顺便帮我看看几点营业？”
Output：你好，评分是4.5分以上，门票100-150
程式在 begin_da() 中的輸出:
![圖片](https://user-images.githubusercontent.com/11405478/98641575-f50f7780-2366-11eb-87ce-5128a3813e1e.png)

想請教一下，在這個 module 中，為什麼會設計成同一個輸入，有不同輸出，又在 rule base 的情況下，我希望有相同的輸出，應該怎麼修正會比較好?

先謝謝您的閱讀，期待您的回覆

**Comment by zqwerty** [comment]
active_tuples_num是模拟用户发射请求的随机性。你这里的input是什么？

**Comment by alznn** [comment]
> 
> 
> active_tuples_num是模拟用户发射请求的随机性。你这里的input是什么？

我的 input 是直接輸入問題，仿造 Getting_Started.ipynb 的寫法，直接給定 sys_response = user_agent.response("你好，麻烦帮我推荐一个门票免费的景点。")
p.s. 例句取自 paper

**Comment by zqwerty** [comment]
> > active_tuples_num是模拟用户发射请求的随机性。你这里的input是什么？
> 
> 我的 input 是直接輸入問題，仿造 Getting_Started.ipynb 的寫法，直接給定 sys_response = user_agent.response("你好，麻烦帮我推荐一个门票免费的景点。")
> p.s. 例句取自 paper

为什么你要用user_agent回复user的话呢？

**Comment by alznn** [comment]
喔喔 應該是我命名沒有改完全，他完整的流程是這樣的 : 
user_agent = PipelineAgent(sys_nlu, sys_dst, sys_policy, sys_nlg, name='sys')
sys_response = user_agent.response("你好，麻烦帮我推荐一个门票免费的景点。")

**Comment by alznn** [comment]
這邊也附上我模仿 Getting_Started.ipynb 所建立的程式碼 (也有附上另一個 issue ) 中
```
# common import: convlab2.$module.$model.$dataset
from convlab2.nlu.jointBERT.crosswoz import BERTNLU
# from convlab2.dst.rule.multiwoz import RuleDST
from convlab2.dst.rule.crosswoz import RuleDST
from convlab2.policy.rule.crosswoz import Simulator
# from convlab2.nlg.template.multiwoz import TemplateNLG
from convlab2.nlg.sclstm.crosswoz import SCLSTM
from convlab2.dialog_agent import PipelineAgent, BiSession
# from convlab2.evaluator.multiwoz_eval import MultiWozEvaluator

from pprint import pprint
import random
import numpy as np
import torch
from opencc import OpenCC

sys_nlu = BERTNLU()
# not use dst
# sys_dst  = RuleDST()
sys_dst = None
# # rule policy
sys_policy  = Simulator()
# template NLG
# user_nlg = TemplateNLG(is_user=True)
sys_nlg  = model_sys = SCLSTM(is_user=False, use_cuda=True)

# # assemble
user_agent = PipelineAgent(sys_nlu, sys_dst, sys_policy, sys_nlg, name='sys')

sys_response = user_agent.response("你好，麻烦帮我推荐一个门票免费的景点。")
#，麻烦帮我推荐一个门票免费的景点。
print("answer:", sys_response)
# print("answer:",user_agent.response("您好，我想找一家评分是4.5分以上、做金牌烤鸭好吃的餐馆，有什么地方呀？顺便帮我看看几点营业？"))
print(" START TO TYPE ")
input()
while True:
    print("######################################################")
    user_response = input("answer: ")
    #user_response = '麻煩我推薦一個免費門票的景點'
    print("user_agent: ",user_response)
    cc = OpenCC('t2s')
    user_response = cc.convert(user_response)
    print("繁簡轉換:",user_response)
    sys_response = user_agent.response(user_response)
    print("answer:", sys_response)
    input()
```

**Comment by zqwerty** [comment]
crosswoz没有rule policy。rule simulator是user的policy

**Comment by alznn** [comment]
了解，我好像懂了，rule simulator 是 training 用的

也就是說 若我想接 sys 的 policy ，應該是要接到 mle 或是 vector 的模組對嗎?
此時就是走完整的 nlu > dst > policy > nlg 的串接流程對嗎?

**Comment by zqwerty** [comment]
> 了解，我好像懂了，rule simulator 是 training 用的
> 
> 也就是說 若我想接 sys 的 policy ，應該是要接到 mle 或是 vector 的模組對嗎?
> 此時就是走完整的 nlu > dst > policy > nlg 的串接流程對嗎?

对
