### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by alznn** [thu-coai/ConvLab-2#160]
https://github.com/thu-coai/ConvLab-2/blob/6f7fbdc9ef664363c1ded0d6cb6de108064b2579/convlab2/policy/rule/crosswoz/rule_simulator.py#L123

使用 crosswoz  的資料集，並做以下設定
```
sys_nlu = BERTNLU()
sys_dst  = RuleDST()
#sys_dst = None
sys_policy  = Simulator()
sys_nlg  = model_sys = SCLSTM(is_user=False, use_cuda=True)
user_agent = PipelineAgent(sys_nlu, sys_dst, sys_policy, sys_nlg, name='sys')

sys_response = user_agent.response("你好，麻烦帮我推荐一个门票免费的景点。")
while True:
    user_response = input("answer: ")
    cc = OpenCC('t2s')
    user_response = cc.convert(user_response)
    sys_response = user_agent.response(user_response)
    print("answer:", sys_response)
```
在 policy 部分選用 rule module 時，同時使 sys_response = user_agent.response(user_response) 可重複輸入 (亦即多輪對話) ，
當程式執行到 while 階段，self.turn_num > 0 時，進入到 rule policy  的 state_update 會爆 **too many values to unpack** 的錯誤，
 convlab2.policy.rule.crosswoz.rule_simulator.py 的執行流程可參考下圖 
![圖片](https://user-images.githubusercontent.com/11405478/98812223-0f2b8180-245d-11eb-9074-b17fceacc0a8.png)

![圖片](https://user-images.githubusercontent.com/11405478/98812046-c247ab00-245c-11eb-839a-2775671c03c3.png)
![圖片](https://user-images.githubusercontent.com/11405478/98812152-f0c58600-245c-11eb-8117-f227a5fc3fb1.png)

**此錯誤發生的原因為：** state_update 的輸入並不相同，迴圈卻用一樣的做法，導致執行時噴調
![圖片](https://user-images.githubusercontent.com/11405478/98812412-6893b080-245d-11eb-9872-8775aa73db17.png)

若將程式  BERTNLU 的結果**直接送至 policy**（直接將 dst = None，跳過不執行），則可以正常執行該迴圈，但會造成**不論輸入什麼資料，程式一率回傳"好的"作為答案**
ˊ
![圖片](https://user-images.githubusercontent.com/11405478/98811706-3afa3780-245c-11eb-9e38-5c924a394c40.png)

想請教這部分應該是屬於 policy 的問題，或是在貴團隊在使用 rule_simulator 的 policy model 時，本來就預期要將 dst 設成 None 直接執行呢?

**Comment by zqwerty** [comment]
rule_simulator 是user 的policy，内部有user state，记录的是目标的完成情况，与sys agent的policy不一样。rule simulator不需要dst

**Comment by alznn** [comment]
> 
> 
> rule_simulator 是user 的policy，内部有user state，记录的是目标的完成情况，与sys agent的policy不一样。rule simulator不需要dst

cool !
那想進一步請問一下，

1.  是只有針對 crosswoz 的 rule simulator 的的 policy 不需接 dst 嗎?
因為以 mcrosswoz作為範例的 Getting_Started.ipynb 檔案中 ， 使用 RulePolicy 前面一層仍須接 rule dst，
```
# go to README.md of each model for more information
# BERT nlu
sys_nlu = BERTNLU()
# simple rule DST
sys_dst = RuleDST()
# rule policy
sys_policy = RulePolicy()
# template NLG
sys_nlg = TemplateNLG(is_user=False)
# assemble
sys_agent = PipelineAgent(sys_nlu, sys_dst, sys_policy, sys_nlg, name='sys')
```
2.  若我接下來想將中間的 policy 換成 DQN 或是 MLE 的資料，是否也要仿造  Getting_Started.ipynb  接上 DST 的 layer 資訊?

下方為我仿造 Getting_Started.ipynb 所建立的 crosswoz 的程式碼，若我對整個串接的理解上有任何理解錯誤，懇請指教

```
# common import: convlab2.$module.$model.$dataset
from convlab2.nlu.jointBERT.crosswoz import BERTNLU
# from convlab2.dst.rule.multiwoz import RuleDST
from convlab2.dst.rule.crosswoz import RuleDST
from convlab2.policy.rule.crosswoz import Simulator
# from convlab2.nlg.template.multiwoz import TemplateNLG
from convlab2.nlg.sclstm.crosswoz import SCLSTM
from convlab2.dialog_agent import PipelineAgent, BiSession
# from convlab2.evaluator.multiwoz_eval import MultiWozEvaluator

from pprint import pprint
import random
import numpy as np
import torch
from opencc import OpenCC

sys_nlu = BERTNLU()
# not use dst
# sys_dst  = RuleDST()
sys_dst = None
# # rule policy
sys_policy  = Simulator()
# template NLG
# user_nlg = TemplateNLG(is_user=True)
sys_nlg  = SCLSTM(is_user=False, use_cuda=True)

# # assemble
user_agent = PipelineAgent(sys_nlu, sys_dst, sys_policy, sys_nlg, name='sys')

sys_response = user_agent.response("你好，麻烦帮我推荐一个门票免费的景点。")
#，麻烦帮我推荐一个门票免费的景点。
print("answer:", sys_response)
# print("answer:",user_agent.response("您好，我想找一家评分是4.5分以上、做金牌烤鸭好吃的餐馆，有什么地方呀？顺便帮我看看几点营业？"))
print(" START TO TYPE ")
input()
while True:
    print("######################################################")
    # user_response = input("answer: ")
    user_response = '麻煩我推薦一個免費門票的景點'
    print("user_agent: ",user_response)
    cc = OpenCC('t2s')
    user_response = cc.convert(user_response)
    print("繁簡轉換:",user_response)
    sys_response = user_agent.response(user_response)
    print("answer:", sys_response)
    input()
```
3. 最後，若上述程式碼串接流程無誤，在最後 while 內的 sys_response = user_agent.response(user_response)，不論輸入為和，均回傳 " 好的 " 作為解答，但我在各 module 按照 document 訓練出來的結果，與 document 提供的結果是一致的，想請教這部分貴團隊在使用時是否有遇到相同的問題，或是是否有其他推測的原因?

**Comment by zqwerty** [comment]
> 是只有針對 crosswoz 的 rule simulator 的的 policy 不需接 dst 嗎?
因為以 mcrosswoz作為範例的 Getting_Started.ipynb 檔案中 ， 使用 RulePolicy 前面一層仍須接 rule dst，

rule simulator 是模拟用户的policy，不需要dst，类比multiwoz的agenda policy

> 若我接下來想將中間的 policy 換成 DQN 或是 MLE 的資料，是否也要仿造 Getting_Started.ipynb 接上 DST 的 layer 資訊?
需要

你的代码用rule simulator作为sys agent，是错误的。

**Comment by alznn** [comment]
了解，我好像懂我在哪部分誤會了，應該是要用 mle 的 module 才對
