### ISSUE TITLE
[BUG] DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by ares5221** [thu-coai/ConvLab-2#162]
**Describe the bug**

**To Reproduce**

when i ran convlab2/nlu/evalute.py, it occur
Please note and check the following:

  * The Python version is: Python3.6 from "E:\conda\anaconda\envs\pytorch\python.exe"
  * The NumPy version is: "1.19.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: 找不到指定的模块。

**Expected behavior**

**Additional context**

**Comment by zqwerty** [comment]
See the comment in `evaluate.py`:
> Usage: python evaluate.py [CrossWOZ|MultiWOZ|Camrest] [BERTNLU|MILU|SVMNLU] [usr|sys|all]

Not sure what's going on with `DLL load failed: 找不到指定的模块。`

**Comment by zqwerty** [comment]
have you installed convlab-2 first?

**Comment by zqwerty** [comment]
feel free to re-open this issue if you have any problem
