### ISSUE TITLE
Complete-rate vs Success-Rate[Feature] 

### ISSUE THREAD

**Issue by ChrisGeishauser** [thu-coai/ConvLab-2#165]
I am wondering about some specifics of the goal evaluation for complete-rate and success-rate. I am constraining myself to semantic level here, i.e. we obtain the ground-truth NLU output.

Success-rate will be evaluated if I use 
        env = Environment(None, simulator, None, dst_sys, evaluator=evaluator)

instead of 
        env = Environment(None, simulator, None, dst_sys, evaluator=None)

I want to illustrate the question on an example. Let's say the goal is G = (C, R), with constraints C=(hotel-area=west, hotel-pricerange=cheap) and requests R=(hotel-address)

The dialogue goes as follows:

User: I want a cheap hotel.
System: Kittycat is a nice hotel. The address is ***.

After that turn, does the user-agenda say that the goal is fulfilled because it can not check if the given hotel fulfills the constraint area=west?

Or does it first ask whether this hotel is in the west, i.e. producing a request-area on the stack? If the system then does not confirm, will it inform on area=west? That is at least what I would expect.

The reason I ask is because I experience a difference between complete-rate and success-rate, which means that the hotel that is booked does not fulfill the constraints by the user. But since we work on semantic-level, all the constraints in the state should be the correct constraints. So if the hotel does not fulfill the constraints of the goal, that means not all constraints were informed by the user and the policy can not know that. 

Moreover in convlab2/policy/rule/multiwoz/policy_agenda_multiwoz.py in function _reward(self) in line 142:

        if self.goal.task_complete():
            reward = 2.0 * self.max_turn
        elif self.agenda.is_empty():
            reward = -1.0 * self.max_turn
        else:
            reward = -1.0
        return reward

Shouldn't task_complete() be only evaluated if self.agenda.is_empty()?

If it is not empty this would mean the user has not informed on something yet (which would then lead to a possible failure of the policy because it did not know about that constraint) or user has not requested something yet.

To conclude: If the policy suggests an entity and there is still some missing constraint that should be informed on: Before we evaluate success or failure, we first need to request the missing constraint, possible informing afterwards on it. And we should only check success or failure after the dialogue has terminated.

In that way, success-rate and complete-rate should be the same on semantic level?

What is your opinion about that and what does the current implementation do here?

Moreover, my policy learns really quickly using evaluator=None but fails with evaluator=MultiWozEvaluator(). That is why i am really interested in the exact difference here.

Thank you very very much in advance!

**Comment by zqwerty** [comment]
> Or does it first ask whether this hotel is in the west, i.e. producing a request-area on the stack? If the system then does not confirm, will it inform on area=west? That is at least what I would expect.

Yes, the agenda simulator will not accept the recommendation until it has informed all of the constraints.

The success-rate and complete-rate would be the same if the goal has been filled consistently with the database

**Comment by ChrisGeishauser** [comment]
Thanks a lot for the quick answer!

> The success-rate and complete-rate would be the same if the goal has been filled consistently with the database

User:  [['Inform', 'Train', 'Dest', 'leicester'], ['Inform', 'Train', 'Day', 'tuesday'], ['Inform', 'Train', 'Leave', '20:45'], ['Inform', 'Train', 'Depart', 'peterborough']]
Sys:  [['Inform', 'Train', 'Choice', '404'], ['Inform', 'Train', 'Leave', '05:00'], ['Request', 'Train', 'Day', '?']]
User:  [['Inform', 'Train', 'Day', 'tuesday']]
Sys:  [['OfferBook', 'Train', 'Leave', '05:00']]
User:  [['Inform', 'Train', 'Leave', '20:45']]
Sys:  [['Inform', 'Train', 'Arrive', '05:51'], ['Inform', 'Train', 'Dest', 'london kings cross'], ['Inform', 'Train', 'Id', 'TR9536'], ['Inform', 'Train', 'Leave', '05:00'], ['Inform', 'Train', 'Ticket', '23.60 pounds'], ['reqmore', 'general', 'none', 'none']]

This is one case where complete-rate is 1 but success-rate is 0. But the filling of values only happens in lexicalization. Is this then a bug in the lexicalization function that decreases success-rate?

**Comment by zqwerty** [comment]
According to the TrainID: TR9536, the system uses the following entity in the database:
```
{
        "arriveBy": "05:51",
        "day": "tuesday",
        "departure": "cambridge",
        "destination": "london kings cross",
        "duration": "51 minutes",
        "leaveAt": "05:00",
        "price": "23.60 pounds",
        "trainID": "TR9536"
    }
```
which does not satisfy the use goal `'Dest', 'leicester'`.

**Comment by ChrisGeishauser** [comment]
Ah I didn't see the updated code about db.query and dbquery_domain, that changed it! Thanks!
