### ISSUE TITLE
[Feature] can this support multi-user conversation with agent

### ISSUE THREAD

**Issue by ares5221** [thu-coai/ConvLab-2#166]
**Describe the feature**
A clear and concise description of what the feature is.
可以支持同时与多个用户进行对话吗？
**Expected behavior**

**Additional context**
Add any other context about the feature here.

**Comment by zqwerty** [comment]
Do you mean one system chats with multiple user agents simultaneously? Currently, the framework only supports one-to-one conversation (`BiSession` class)

**Comment by ares5221** [comment]
> Do you mean one system chats with multiple user agents simultaneously? Currently, the framework only supports one-to-one conversation (`BiSession` class)

got it, thks for reply, great job
