### ISSUE TITLE
Environment reset

### ISSUE THREAD

**Issue by ChrisGeishauser** [thu-coai/ConvLab-2#167]
When a policy is trained, at the start of the episode we have (for instance in convlab2/policy/ppo/train.py function sampler):

s = env.reset()
s is the default dialogue state here.

and then the policy uses that default state to act. So the policy has no information at all and should just greet I guess.

But in the MultiWOZ dataset, the user begins the conversation, so should we change the following:

In convlab2/dialog_agent/env.py in function reset:

    def reset(self):
        self.usr.init_session()
        self.sys_dst.init_session()
        if self.evaluator:
            self.evaluator.add_goal(self.usr.policy.get_goal())

        s, r, t = self.step([]) #This is the new line
        return self.sys_dst.state

**Comment by zqwerty** [comment]
Thanks!
