### ISSUE TITLE
[Feature] how to train dqn with my own data, how to constract goal data

### ISSUE THREAD

**Issue by ares5221** [thu-coai/ConvLab-2#168]
**Describe the feature**
A clear and concise description of what the feature is.
my data have 12 slot then system inform a reason info,
now i want to train model with my data, and how to set data format

**Expected behavior**

**Additional context**
Add any other context about the feature here.

**Comment by zqwerty** [comment]
We are unifying the data preprocess. https://github.com/thu-coai/ConvLab-2/issues/55#issuecomment-797884836
