### ISSUE TITLE
Benchmark Table

### ISSUE THREAD

**Issue by lalapo** [thu-coai/ConvLab-2#172]
Why the benchmark table shows very bad result of the methods that reach state-of-the-arts performance in Multiwoz benchmark table? And also like, GDPL, why it performs very bad under this framework?

**Comment by zqwerty** [comment]
We evaluate the performance in end-to-end fashion, which may not be consistent with the component-wise evaluation. You can refer to https://arxiv.org/pdf/2005.07362.pdf for more details using ConvLab
