### ISSUE TITLE
[BUG] Illegal dialog acts from RuleBasedMultiwozBot

### ISSUE THREAD

**Issue by ghost** [thu-coai/ConvLab-2#173]
**Describe the bug**
RuleBasedMultiwozBot returns some dialog acts that are not belong to neither "sys_da_voc.txt" nor "da_slot_cnt.json".

**To Reproduce**
1. Go to 'convlab2/policy/rule/multiwoz/rule_based_multiwoz_bot.py'
2. Scroll down to ‘predict' method of class 'RuleBasedMultiwozBot'. Add a checkpoint at the begining of this method, e.g., 
```python
if 'user_action' in state:
    if ['Inform', 'Hospital', 'Department', 'trauma and orthopaedics'] in state['user_action']:
        print(state)
```
3. Run a session, where system side contains RuleDST and RuleBasedMultiwozBot, and user side contains UserPolicyAgendaMultiWoz.
4. After seeing that the conditions of step 2 are met, the return of 'predict' method should be something like this
```python
[['Inform', 'Hospital', 'Choice', '2'],
['Recommend', 'Hospital', 'Department', 'trauma and orthopaedics']]
```
These two dialog acts are not belong to neither "sys_da_voc.txt" nor "da_slot_cnt.json" (these two files are in data/multiwoz). I don't know whether there is something went wrong with the rule-bot or the two files are missing some important dialog acts.

**Expected behavior**
The action of rule-bot should be consistent with the provided dialogue acts in the two files.

**Comment by zqwerty** [comment]
"sys_da_voc.txt" and "da_slot_cnt.json" are extracted from the multiwoz dataset, which may not cover all possible dialog acts. In this case, there are two "trauma and orthopaedics" departments available in the database (hospital_db.json, id=10, 19), so the RuleBasedMultiwozBot inform 2 choices and recommend one, as other domains.

**Comment by ghost** [comment]
> "sys_da_voc.txt" and "da_slot_cnt.json" are extracted from the multiwoz dataset, which may not cover all possible dialog acts. In this case, there are two "trauma and orthopaedics" departments available in the database (hospital_db.json, id=10, 19), so the RuleBasedMultiwozBot inform 2 choices and recommend one, as other domains.

I get it. But in dqn, we use "sys_da_voc.txt" by default for single action instead of all possible actions. Does it make sense? Or is it more appropriate to use all posible dialog acts as the outputs of dqn?

**Comment by zqwerty** [comment]
> > "sys_da_voc.txt" and "da_slot_cnt.json" are extracted from the multiwoz dataset, which may not cover all possible dialog acts. In this case, there are two "trauma and orthopaedics" departments available in the database (hospital_db.json, id=10, 19), so the RuleBasedMultiwozBot inform 2 choices and recommend one, as other domains.
> 
> I get it. But in dqn, we use "sys_da_voc.txt" by default for single action instead of all possible actions. Does it make sense? Or is it more appropriate to use all posible dialog acts as the outputs of dqn?

I think using all posible dialog acts for single action is appropriate. However, since there may exist enormous possible dialog acts combinations, some combinations of low-frequency can be ignored.

**Comment by ghost** [comment]
OK. Thanks a lot.
