### ISSUE TITLE
Lexicalization of action[BUG] 

### ISSUE THREAD

**Issue by ChrisGeishauser** [thu-coai/ConvLab-2#176]
In ConvLab-2/convlab2/util/multiwoz/lexicalize.py in line 57:

Shouldn't it be "if REF_SYS_DA[domain][pair[0]] in state[domain.lower()]['semi']:" instead of "if pair[0] in state[domain.lower()]['semi']:"?

**Comment by zqwerty** [comment]
Thank you! We've fixed this.
