### ISSUE TITLE
關於 vector_crosswoz.py 程式碼的問題

### ISSUE THREAD

**Issue by ivy2315** [thu-coai/ConvLab-2#187]
您好，最近在研究貴團隊開發的系統，在深入了解程式碼的過程中，對於 vector_crosswoz.py 裡面 state_vectorize的部分code有些疑問，如下圖
![image](https://user-images.githubusercontent.com/67856226/113567182-b09bb580-9640-11eb-9bd3-c7c70bdb5dbd.png)
想了解貴團隊這裡的 db_res_vec 用 db_res_num 判斷然後給予值的原因為何？
感謝

**Comment by zqwerty** [comment]
判断当前的用户约束能找到多少满足条件的结果。=0，可能会说nooffer，如果结果很多，可能再次询问用户是否有其他约束。

**Comment by ivy2315** [comment]
感謝解釋，那我想再進一步詢問，1 < db_res_num < 5 這個部分，5的配置是為什麼？貴團隊對於符合條件的數量多寡，是依據什麼概念，區分成這四個 if else 條件的？

**Comment by zqwerty** [comment]
经验设置，没有特别的理由。如果等于0，可能就是nooffer，=1，可能就推荐一个，(1,5)可能推荐多个，>5可能要求更多的条件。主要是区分不同场景下action可能不同。

**Comment by ivy2315** [comment]
原來如此，那這裡的經驗設置，是會影響到後面的推薦嗎？
也就是說，如果詢問"免費景點"的話，可能符合條件的景點有 400 個，那 db_res_vec = [0, 0, 0, 1] 沒錯吧？
但是我測試出來他始終只會推薦，在 database 裡面第一個符合條件的景點， db_res_vec 這樣的設置會有影響嗎？還是是在 select_action() 裡面才會影響最終的推薦結果？

**Comment by zqwerty** [comment]
在设计的时候我们认为可能会影响后面的推荐，但是实际训练出来的模型不一定很强地依赖这种设计。select_action 是哪里？

**Comment by ivy2315** [comment]
rlmodule 裡面有根據不同情況的 select_action，下圖為 MultiDiscretePolicy 的舉例： 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/67856226/115227814-8c150280-a143-11eb-8817-f92391337fd4.png">
db_res_vec 與其他 vec 疊加後會送進 select_action
<img width="908" alt="image" src="https://user-images.githubusercontent.com/67856226/115228539-7c49ee00-a144-11eb-9927-1d68a653070d.png">
我推測是在這裡決定推薦結果的，從下圖判斷的：
<img width="755" alt="image" src="https://user-images.githubusercontent.com/67856226/115228162-034a9680-a144-11eb-85ec-9acff6600086.png">
不知道是否有判斷錯誤？
問題有點多，真的十分感謝您的回覆！

**Comment by zqwerty** [comment]
应该是的，db_res_vec与其他向量组合作为状态表示，用于选择action
