### ISSUE TITLE
關於 CrossWOZ train RL Policies 的 evaluator 問題

### ISSUE THREAD

**Issue by ivy2315** [thu-coai/ConvLab-2#188]
您好，想使用貴團隊提供的 example_train.py ， 程式碼裡面的 evaluator 為 MultiWozEvaluator() ，想請問您 CrossWOZ 能直接使用嗎？還是要修改哪部分的程式碼？
十分感謝

**Comment by zqwerty** [comment]
CrossWOZ不能直接使用MultiWozEvaluator。可能需要重新实现其中计算success的部分代码。CrossWOZ论文中计算成功率是通过simulator来判断的
