### ISSUE TITLE
MILU Does not work

### ISSUE THREAD

**Issue by jnehring** [thu-coai/ConvLab-2#192]
**Describe the bug**
Cannot import MILU. Running the example, either on Colab or on my own laptop, fails in this line:

```
from convlab2.nlu.milu.multiwoz import MILU
```

**To Reproduce**

1. Goto https://colab.research.google.com/github/thu-coai/ConvLab-2/blob/master/tutorials/Getting_Started.ipynb
2. Execute cells until the first cell under "build an agent"

I attached the error message to this issue.

[stacktrace.txt](https://github.com/thu-coai/ConvLab-2/files/6420750/stacktrace.txt)

**Comment by zqwerty** [comment]
Thanks! it is caused by the update of `overrides` package https://github.com/grammarly/gector/issues/100. Fixed
