### ISSUE TITLE
[BUG] when runing the "Tutorials Getting Started (Have a try on Colab!)"，it is fail to "import convlab2"

### ISSUE THREAD

**Issue by gzpbbd** [thu-coai/ConvLab-2#199]
**Describe the bug**
When runing the "Tutorials Getting Started (Have a try on Colab!)" in tutorials, it is fail to "import convlab2", a wrong happend.
![image](https://user-images.githubusercontent.com/59677941/118785733-b9300e80-b8c3-11eb-902f-6bbce10b819d.png)

the URL of the tutorials is [https://colab.research.google.com/github/thu-coai/ConvLab-2/blob/master/tutorials/Getting_Started.ipynb](https://colab.research.google.com/github/thu-coai/ConvLab-2/blob/master/tutorials/Getting_Started.ipynb)

**To Reproduce**
run the following code in colab of Google:
`! git clone https://github.com/thu-coai/ConvLab-2.git && cd ConvLab-2 && pip install -e .`
`! python -m spacy download en_core_web_sm`
`from convlab2.nlu.jointBERT.multiwoz import BERTNLU`

**Comment by zqwerty** [comment]
you should restart the kernel after install convlab2

**Comment by gzpbbd** [comment]
it works now. sorry, I am new. Thank you.

**Comment by gzpbbd** [comment]
@zqwerty it works now. sorry, I am new. Thank you.

> you should restart the kernel after install convlab2

**Comment by gzpbbd** [comment]
> you should restart the kernel after install convlab2

it works now. sorry, I am new. Thank you.
