### ISSUE TITLE
[Maintenance]: Python 3.7+ support.

### ISSUE THREAD

**Issue by alexcoca** [thu-coai/ConvLab-2#202]
**Describe the feature**
Python 3.6 hits end of life support come December, so in order to use the latest language features and integrate with libraries, convlab2 should support 3.7+.

**Expected behavior**
pip install -e . does not throw any errors when installed in a python 3.8 conda environment.

**Comment by zqwerty** [comment]
thanks! will fix this in a few days

**Comment by zqwerty** [comment]
I've tested on python 3.7&3.8, installed it without  any errors
