### ISSUE TITLE
[BUG] Action ordering in template multiwoz nlg.py

### ISSUE THREAD

**Issue by SpaceHunterInf** [thu-coai/ConvLab-2#204]
**Describe the bug**
Greetings,

It seems like the actions are sorted in reverse order in the function sorted_dialog_act(self, dialog_acts) in nlg.py. On line 103, you have `new_action = new_action_group[domain][k] + new_action` Wouldn't this put all the actions in reverse order? When I was informing something, name always appeared after everything else which makes me think if my model is wrong. But it seems like the nlg creates this issue...

`new_action = new_action + new_action_group[domain][k]`maybe?

BTW: May I ask why you choose to use an Ordereddict as the datastructure of actions on line 115?

Thanks

**Comment by zqwerty** [comment]
> Wouldn't this put all the actions in reverse order?

You're right! fixed it

> BTW: May I ask why you choose to use an Ordereddict as the datastructure of actions on line 115?

to keep the same order as the input dialog acts
