### ISSUE TITLE
error when importing convlab2

### ISSUE THREAD

**Issue by thenickben** [thu-coai/ConvLab-2#21]
This may be a silly issue, but when trying to run the tutorial notebook on Colab, convlab2 doesn't get imported after cloning the repo and installing. This is a sample notebook with the two lines involved:

https://colab.research.google.com/drive/1B6p8_GXoPUau9AaZUnKmCm3hQX8BcsIv?usp=sharing

Thanks!

Nick

**Comment by hrwise-nlp** [comment]
This is caused by the directory level.

you can try 
cd Convlab-2
and process

**Comment by zqwerty** [comment]
You should re-start the notebook after installing

**Comment by thenickben** [comment]
to make it work without re-starting the notebook this should be added before importing convlab2

```
import os

path = os.path.join(os.getcwd(), 'ConvLab-2')
os.chdir(path)
```
