### ISSUE TITLE
[BUG] a tiny bug from tutorial on colab

### ISSUE THREAD

**Issue by froggyis** [thu-coai/ConvLab-2#213]
**Describe the bug**
at the first line
`git clone https://github.com/thu-coai/ConvLab-2.git && cd ConvLab-2 && pip install -e . `

can't work simultaneously

after git clone we still need another line to use cd ConvLab-2 command to get into ConvLab-2 directory to use the following model. I am not sure whether it is only on my machine .the && suppose to work however it didn't

but it is just a little bug

**Comment by zqwerty** [comment]
it works on my computer and colab. won't fix
