### ISSUE TITLE
can you upgrade the version of allennlp to the newest version?

### ISSUE THREAD

**Issue by XuJing1022** [thu-coai/Convlab-2#223]
I cannot install the allennlp==0.9.0 correctly on the plateform of Mac M1.  Can you upgrade the version of allennlp to the newest version, i.e 3.2 ?

**Comment by zqwerty** [comment]
allennlp is only used by [MILU](https://github.com/thu-coai/ConvLab-2/tree/master/convlab2/nlu/milu). If you do not need MILU, just ignore it. you can modify the setup.py yourself. If you want to use MILU, I'm not sure if it is ok to use a higher version of allennlp
