### ISSUE TITLE
[Feature] Any plans to incorporate new models?

### ISSUE THREAD

**Issue by ShaneTian** [thu-coai/Convlab-2#224]
Most of the models in ConvLab-2 are basic and early. Are there plans to incorporate more new models (DST / E2E)?

**Comment by zqwerty** [comment]
yes! we're adding TripPy, [setSUMBT](https://gitlab.cs.uni-duesseldorf.de/general/dsml/setsumbt-public/-/releases), SOLOIST, and [TUS](https://aclanthology.org/2021.sigdial-1.47/) in our private repo, which may be released a few months later.

**Comment by zqwerty** [comment]
@ShaneTian [ConvLab-3](https://github.com/ConvLab/ConvLab-3) release now, new models are available!

**Comment by ShaneTian** [comment]
Excellent 💥
