### ISSUE TITLE
Spacy latest version compatibility

### ISSUE THREAD

**Issue by lluissalord** [thu-coai/Convlab-2#230]
Hi,

On our company, we would like to use ConvLab-2, but we are using spacy models with latest version of Spacy v3.X and I see that for the `setup.py` it is required the 2.1.9 version. 

Looking at the code which is related to the usage of spacy, it seems like it could be compatible with other versions. Besides, looking at `allennlp` (which is one of the dependencies related to Spacy), they have as a requirement `spacy>=2.1.0,<3.3`, hence it would be compatible too.

Could it be possible to use Spacy v3.X with ConvLab-2?

**Comment by zqwerty** [comment]
Sure. I think only MILU needs the low version of `spacy` to be compatible with `allennlp==0.9`

**Comment by lluissalord** [comment]
Okay, perfect thank you for quick the clarification! I am closing this as the question has been resolved.
