### ISSUE TITLE
spacy tokenizer

### ISSUE THREAD

**Issue by IreneSucameli** [thu-coai/ConvLab-2#232]
Hi, the spacy tokenizer in the NLU module (specifically, jointBERT) is downloaded every time the script is launched? Thus, the module downloads the latest version of the tokenizer? Or the version used is fixed? Thanks.

**Comment by zqwerty** [comment]
> the spacy tokenizer in the NLU module (specifically, jointBERT) is downloaded every time the script is launched?

No, I think only the first time. Once downloaded, `self.nlp = spacy.load("en_core_web_sm")` will not raise error

https://github.com/thu-coai/ConvLab-2/blob/ad32b76022fa29cbc2f24cbefbb855b60492985e/convlab2/nlu/jointBERT/multiwoz/nlu.py#L60-L67
