### ISSUE TITLE
Integrating with my own dataset

### ISSUE THREAD

**Issue by youssef-shaker** [thu-coai/Convlab-2#233]
Hi, I am a bachelor student working on creating a chatbot to answer university student questions about regulations and rules, so I was wondering if it is possible to make Conv-Lab work on my own dataset. I found this unified dataset directory I feel it could be used for that. If that is possible I would really appreciate it if you could give me guidance on how to get it working

Thank you in advance

**Comment by zqwerty** [comment]
Currently, we are working on unifying the format of different datasets and updating the dataloaders of our models to support this unified format. Our code is under review and will be made public in 1-2 months. Once released, you can transform your datasets into this unified format and then run all supported models directly!

**Comment by youssef-shaker** [comment]
That is awesome and thank you for replying rapidly. Is it possible to send the code and I try to use it as I really do not have the ability of waiting a month as the deadline is only in days sadly. I would really appreciate it and thank you again

**Comment by zqwerty** [comment]
which model are you going to use?
