### ISSUE TITLE
[BUG] 关于中文数据集crosswoz上policy-rule代码的问题

### ISSUE THREAD

**Issue by sunsunswj** [thu-coai/Convlab-2#234]
**Describe the bug**
在使用中文数据集时，在policy部分会出现，for intent, domain, slot, value in system_action:时候会出现ValueError: too many values to unpack(expected 4)的报错，查询代码发现，prev_sys_da传入数据不只有["system_action"]部分，在修改代码如
system_action = prev_sys_da['system_action']
for intent, domain, slot, value in system_action:
后，发现不能正常多轮对话，主要表现在policy.predict部分的问题，同时似乎是无法读取"Request“部分

**Comment by zqwerty** [comment]
你是用这个https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/policy/rule/crosswoz/rule_simulator.py 作为system policy吗？crosswoz相关代码的使用可以参考原仓库https://github.com/thu-coai/CrossWOZ
