### ISSUE TITLE
Issue in BertNLU

### ISSUE THREAD

**Issue by AtheerAlgherairy** [thu-coai/Convlab-2#237]
I am trying to run ConvLab2 but this line has an error:
 self.nlp.tokenizer.add_special_case(token, [{ORTH: token, LEMMA: token, POS: u'NOUN'}])

Error message:
ValueError: [E1005] Unable to set attribute 'LEMMA' in tokenizer exception for 'cb58nt'. Tokenizer exceptions are only allowed to specify ORTH and NORM.

**Comment by zqwerty** [comment]
Have you installed `spacy==2.1.9`?

**Comment by AtheerAlgherairy** [comment]
Yes.

**Comment by zqwerty** [comment]
I have tried Google Colab with this (spacy==2.1.9 and en_core_web_sm==2.1.0)

![屏幕快照 2022-10-17 下午7 13 46](https://user-images.githubusercontent.com/12478606/196163269-241d67e1-de31-4e96-868d-2332f2f42f7f.png)

I think it is probably a version issue. Could you re-install spacy and install en_core_web_sm?

**Comment by AtheerAlgherairy** [comment]
Yes it was a version issue. 
Thanks for your prompt response.
