### ISSUE TITLE
 Unable to get the pretrained BERTNLU model even after updating the URLs

### ISSUE THREAD

**Issue by bmanasi** [thu-coai/Convlab-2#239]
As per issue #238, I changed the URL of model_file to new hugging face URL but I got the following error:
![image](https://user-images.githubusercontent.com/40319992/200067393-cde820d9-facc-4872-94b3-66522b7839b9.png)
![image](https://user-images.githubusercontent.com/40319992/200067450-8925157b-f102-4e39-b666-9fb19a41d0e4.png)

To resolve this, I tried applying the fix mentioned here : https://stackoverflow.com/questions/3083235/unzipping-file-results-in-badzipfile-file-is-not-a-zip-file

But to no avail. Any idea what I am missing? I am working on colab. Cannot work on local.

**Comment by zqwerty** [comment]
@bmanasi  Maybe you should use `https://huggingface.co/ConvLab/ConvLab-2_models/resolve/main/bert_multiwoz_all_context.zip` (from the download link of hugging face hub) instead of the current one.

**Comment by rizar** [comment]
Can you please update the link in the Colab tutorial? I'm using your Colab for a class, it would be nicer if it worked out of the box.

**Comment by zqwerty** [comment]
> Can you please update the link in the Colab tutorial? I'm using your Colab for a class, it would be nicer if it worked out of the box.

I am not sure what you mean, since the Colab tutorial does not have any model link. I think you are asking for updating the link in the ConvLab-2 code? I will solve this in a week.

**Comment by AtheerAlgherairy** [comment]
> > Can you please update the link in the Colab tutorial? I'm using your Colab for a class, it would be nicer if it worked out of the box.
> 
> I am not sure what you mean, since the Colab tutorial does not have any model link. I think you are asking for updating the link in the ConvLab-2 code? I will solve this in a week.

I tried to update the links in the code.. It works when I changed the URL for BERTNLU. But It doesn't work for the other NLU models (SVM, MILU)..

Waiting for your updates..

Many thanks :)

**Comment by rizar** [comment]
@zqwerty  changing the link in the code will solve the problem, thanks. 

Colab can be fixed quickly by setting `model_file=...` in BERTNLU, but one has to read the code to understand how to do it correctly.

**Comment by zqwerty** [comment]
@rizar @bmanasi @AtheerAlgherairy 
I have replaced the model URL in the ConvLab-2 code with the model URL in our Hugging Face repo. If you try to use trained models of ConvLab-2, make sure to update the code.

**Comment by bmanasi** [comment]
Thanks for your quick response! Will keep this in mind
It works perfectly now.
