### ISSUE TITLE
installation python 3.7 on CentOS7 failed[BUG] 

### ISSUE THREAD

**Issue by SchweitzerGAO** [thu-coai/Convlab-2#241]
I tried to install this on CentOS with python 3.7 but it seemed to fail when installing some of the dependency I am not sure if you support Linux installation
Here are what I saw

![image](https://user-images.githubusercontent.com/64410968/210972486-e2ef954c-d0db-49a9-8e9e-378d760bb685.png)
---
![image](https://user-images.githubusercontent.com/64410968/210972641-0b058a01-153f-4a06-9602-64cc89d837fd.png)
---
![image](https://user-images.githubusercontent.com/64410968/210972773-0c85cf78-1802-47e4-9d14-881af44444b7.png)

**Comment by zqwerty** [comment]
We've tested on Ubuntu. I think CentOS should also work. Could you install the `jsonnet` manually and try again?

**Comment by SchweitzerGAO** [comment]
Thanks but I will turn to convlab-3 haha 😄
