### ISSUE TITLE
The Link to the datasets of LAUG is unreachable 

### ISSUE THREAD

**Issue by zzysjtuiwct** [thu-coai/Convlab-2#242]
Hi, the Link to the datasets resolves to an unreachable IP Address: http://115.182.62.174:9876/

**Comment by zqwerty** [comment]
Sorry, the server that hosts this data is turned off.

**Comment by zqwerty** [comment]
We upload the data here: https://huggingface.co/ConvLab/ConvLab-2_models/blob/main/laug.zip

**Comment by zzysjtuiwct** [comment]
Many thanks!
