### ISSUE TITLE
是否可以使用不经过训练后的BERTNLU呢

### ISSUE THREAD

**Issue by suntea233** [thu-coai/ConvLab-2#245]
是否可以做一个ZERO-SHOT的BERTNLU呢

**Comment by zqwerty** [comment]
可以参考使用槽位描述的相关工作，**依次**将意图/槽位描述作为输入，抽取对应的槽值
1. [Zero-Shot Adaptive Transfer for Conversational Language Understanding](https://arxiv.org/pdf/1808.10059.pdf)
2. [Robust Zero-Shot Cross-Domain Slot Filling with Example Values](https://aclanthology.org/P19-1547.pdf)
3. [Dialogue State Tracking with a Language Model using Schema-Driven Prompting](https://aclanthology.org/2021.emnlp-main.404)

**Comment by suntea233** [comment]
好的，谢谢

**Comment by zqwerty** [comment]
@suntea233 我们在ConvLab-3提供了一个简单的基于LLM的NLU （zero-shot/few-shot）：https://github.com/ConvLab/ConvLab-3/blob/master/convlab/base_models/llm/nlu.py

**Comment by suntea233** [comment]
好的,辛苦了!

**Comment by suntea233** [comment]
我尝试了一下,感觉目前的LLM还是不适合做这种固定的格式的解析工作,能否尝试通过这种形式输出呢?
intent: xxx
domain: xxx
slot: xxx
value: xxx

**Comment by zqwerty** [comment]
你可以尝试一下。我感觉可能差距不大。主要还是看大模型本身遵循指令能力的强弱。我觉得主要的问题是难以通过少量样本覆盖标签空间，让大模型理解各标签的判断标准。

**Comment by suntea233** [comment]
好的，谢谢
