### ISSUE TITLE
[Feature] integrate SimpleTOD into ConvLab-2

### ISSUE THREAD

**Issue by zqwerty** [thu-coai/ConvLab-2#25]
**Describe the feature**
[SimpleTOD](https://arxiv.org/pdf/2005.00796.pdf) perform strongly on the MultiWOZ dataset. It can be used in DST, Policy, and end-to-end tasks.

**Expected behavior**
Can use SimpleTOD as DST, Policy, and end-to-end model.

**Additional context**
Performance: https://github.com/budzianowski/multiwoz

**Comment by unparalleled-ysj** [comment]
Is it integrated into this repo?

**Comment by zqwerty** [comment]
No. We've used it but its training & inference is too slow. We're incorporating SOLOIST instead.

**Comment by unparalleled-ysj** [comment]
Very nice job, is there a release schedule for SOLOIST？

**Comment by zqwerty** [comment]
Not sure. Still working on it with the SOLOIST author. Maybe in a month
