### ISSUE TITLE
help

### ISSUE THREAD

**Issue by AnnaZhaoZhao** [thu-coai/ConvLab-2#27]
when I use the interactive tool, I can't find the tool in browser after runing run.py. What's wrong happend, or where should I modify? Can you tell me what should i do? thanks!

**Comment by zqwerty** [comment]
Could you please provide more details? What's your configuration of deployment?

**Comment by AnnaZhaoZhao** [comment]
I just modify the host at run.py, and then run the .py file by python run.py

if __name__ == '__main__':
    # gunicorn deploy.run:app --threads 4
    app.run(host='10.112.79.206', port=dep_conf['net']['port'], debug=True)

Then it appeared this:

 * Running on http://10.112.79.206:8787/ (Press CTRL+C to quit)

 * Debugger is active!
 * Debugger PIN: 280-719-948

After I open http://10.112.79.206:8787/ with my browser, 404 appeared:

10.38.21.234 - - [19/Jun/2020 10:36:15] "GET / HTTP/1.1" 404 -
10.38.21.234 - - [19/Jun/2020 10:36:15] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by hrwise-nlp** [comment]
http://10.112.79.206:8787/dialog
pls try this

**Comment by AnnaZhaoZhao** [comment]
> http://10.112.79.206:8787/dialog
> pls try this

Thanks！Love you!
