### ISSUE TITLE
[BUG] Sequicity

### ISSUE THREAD

**Issue by yclzju** [thu-coai/ConvLab-2#28]
I find the result of sequicity is quite bad in convlab2(e2e/sequicity), and when I print the result, it's something like this:
user: May I have the address ?
sys: the address is .
I try to train the sequicity in convlab2, the test result is at least not so bad as the result by running the script. So I wonder if there are some bugs in sequicity inference.

**Comment by truthless11** [comment]
@yclzju Thanks for reporting the problem. Could you provide us more details on the bad cases you found? We'll fix it before long.

**Comment by yclzju** [comment]
When I run the test script in tests/test_Sequicity.py
The result is something like this:

user: Actually I need a expensively priced restaurant . Are there any fitting that description ?
sys: i have found the in the , and the address is .

user: May I have the address ?
sys: the address is .

user: May I have the address ?
sys: the address is .

user: Thank you . May I have the address ?
sys: the address is .

user: Please give me their address .
sys: the address is , the address is , the address is , the address is . can i help you with that ?

user: May I also get the address for the restaurant ?
sys: the address is , the address is , the address is , the address is , the address is , the address is , the address is , the address is ,

**Comment by yclzju** [comment]
I think this bug comes from the db query.

**Comment by truthless11** [comment]
> I think this bug comes from the db query.

I've checked the DB query, but the bug does not come from it. We will try to figure out the error.
