### ISSUE TITLE
[BUG] Some code problems

### ISSUE THREAD

**Issue by zyds** [thu-coai/ConvLab-2#34]
When I try to run the evaluate command of “Translation-train SUMBT for cross-lingual DST”, I foud some code problems. 

1. convlab2/dst/sumbt/multiwoz_zh/sumbt.py , line 33
    `DOWNLOAD_DIRECTORY = os.path.join(SUMBT_PATH, 'pre-trianed')`
    Maybe 'pre-trianed' should be changed to 'pre-trained'
2. convlab2/dst/sumbt/multiwoz_zh/convert_to_glue_format.py , line 126,  
    `value = value_trans.get(value, value)`
    Maybe  `value_trans.get(value, value)` should be `trans_value(value)`
3. convlab2/dst/sumbt/crosswoz_en/sumbt.py , line 36 (same as no.1)
    `DOWNLOAD_DIRECTORY = os.path.join(SUMBT_PATH, 'pre-trianed')`
    Maybe 'pre-trianed' should be changed to 'pre-trained'

**Comment by zqwerty** [comment]
Thanks! We've fixed the bugs
