### ISSUE TITLE
Can ConvLab-2 be used for my private dataset?

### ISSUE THREAD

**Issue by tristatl** [thu-coai/ConvLab-2#58]
Hi, I want to know how can I train models in ConvLab-2  on my private dataset to build my own task-oriented dialogue system?

**Comment by thenickben** [comment]
From my understanding I think it would require some efforts to adapt it to your dataset. I guess though this depends on what kind of Dialogue System you want to build (e.g. e2e vs just the policy). For example, for an agenda policy (user) check multiwoz and you'll notice it's very customised to this very dataset. From the system perspective, if you want to use an RL algorithm (either those in the library or implement one of your own) I think it's much easier, given it's good quality code and design (well, this is in general, it is a good library). Perhaps @zqwerty can correct me if I'm wrong. Cheers!

**Comment by zqwerty** [comment]
> From my understanding I think it would require some efforts to adapt it to your dataset. I guess though this depends on what kind of Dialogue System you want to build (e.g. e2e vs just the policy). For example, for an agenda policy (user) check multiwoz and you'll notice it's very customised to this very dataset. From the system perspective, if you want to use an RL algorithm (either those in the library or implement one of your own) I think it's much easier, given it's good quality code and design (well, this is in general, it is a good library). Perhaps @zqwerty can correct me if I'm wrong. Cheers!

That's right. To build a dialogue system in a new dataset, you can train the model with some modification for data processing.

**Comment by tristatl** [comment]
> From my understanding I think it would require some efforts to adapt it to your dataset. I guess though this depends on what kind of Dialogue System you want to build (e.g. e2e vs just the policy). For example, for an agenda policy (user) check multiwoz and you'll notice it's very customised to this very dataset. From the system perspective, if you want to use an RL algorithm (either those in the library or implement one of your own) I think it's much easier, given it's good quality code and design (well, this is in general, it is a good library). Perhaps @zqwerty can correct me if I'm wrong. Cheers!

Thanks for your advices. My dataset is in Chinese language. So if I want to build a Dialogue Syste in pipeline form, do I need modify all the part(nlu,dst,policy,nlg)? And  if I just want to use an RL algorithm in the library and apply it  to my private data, so what I should do is to modify the code in policy part(add some code about data processing)?  
I am new to this domain. Thanks again for your patience.

**Comment by zqwerty** [comment]
> So if I want to build a Dialogue Syste in pipeline form, do I need modify all the part(nlu,dst,policy,nlg)?

Yes

> And if I just want to use an RL algorithm in the library and apply it to my private data, so what I should do is to modify the code in policy part(add some code about data processing)?

You also need a user simulator for your RL policy training.
