### ISSUE TITLE
Is there any method to add DQN to convlab2?

### ISSUE THREAD

**Issue by sherlock1987** [thu-coai/ConvLab-2#59]
Hey, guys, I am a big fan of Convlab1, and in that platform, it implement the actor critic, ppo and also DQN. Are you guys plan to add these two other RL model to convlab2? If not, is there any convinient way for me to add these RL methods?

**Comment by zqwerty** [comment]
In multi-domain dialogue, multiple actions are common. DQN cannot solve this directly. In ConvLab, most frequent dialogue act combinations are considered as actions, which could not cover every possible dialogue act combinations. However, we welcome your contributions to adding more RL methods. You can follow the structure of the existing RL policy in ConvLab-2. Look forward to your success!

**Comment by sherlock1987** [comment]
Hey, since my focus point is in RL-Reward function part, so for me there are not so much RL policies I could use, there are only PPO, and PG, is there any other RL methods I could implement in this platform? 

I have made some statics, you are right, there are more than 8000 actions in this Multi Domain dataset.

**Comment by zqwerty** [comment]
You could try DQN, A3C, A2C, or any other that you are interested in.

**Comment by sherlock1987** [comment]
Thanks, I am not sure if DQN will work. Since in Convlab1, there are only 300 combination of actions in total, but in convlab2 it will be more than 8000. When using same dataset, did you know why the combination of Convlab2 is so much?

**Comment by sherlock1987** [comment]
Hey, about the action space, do you gays have some clue? Like should I add some model of action encoder to Convlab2? So I can narrow the action space from 8000 to 300, by only considering the most frequent actions.

**Comment by zqwerty** [comment]
In ConvLab, we select the most frequent action combinations from all combinations in the dataset (https://github.com/ConvLab/ConvLab/blob/master/data/multiwoz/da_slot_cnt.json). You can try this approximation in ConvLab-2, too.

**Comment by truthless11** [comment]
Please refer to #96
