### ISSUE TITLE
What is different between MultiWOZ 2.1 dataset `train.json.zip`, `train_corrected.json.zip` and `MultiWOZ2.1_Cleaned.zip`?

### ISSUE THREAD

**Issue by ShaneTian** [thu-coai/ConvLab-2#61]
- `train.json.zip`: https://github.com/thu-coai/ConvLab-2/blob/master/data/multiwoz/train.json.zip
- `train_corrected.json.zip`: https://github.com/thu-coai/ConvLab-2/blob/master/data/multiwoz/train_corrected.json.zip
- `MultiWOZ2.1_Cleaned.zip`: https://github.com/ConvLab/ConvLab-2/blob/master/data/multiwoz/MultiWOZ2.1_Cleaned.zip

**Comment by truthless11** [comment]
@ShaneTian We have polished the **user dialog act annotation** in ConvLab-2.  You can just use the latest version of MultiWoz: `MultiWOZ2.1_Cleaned.zip`.  Please refer to the `ReadMe` file in it for more details on the data correction.
