### ISSUE TITLE
[BUG] init_session class method

### ISSUE THREAD

**Issue by thenickben** [thu-coai/ConvLab-2#63]
**Describe the bug**
Not quite a bug but I've noticed some policies (like PPO and PG) have an `init_session` method that is not implemented, yet it's called by the agent (dialog_agent/agent.py) when the pipeline is build. Is this a non-used method or is there any plan of adding something here?

**Comment by liangrz15** [comment]
The `init_session` method is used to initialize the attributes of policy, if needed. Rule-based policy does implement this method, while PPO and PG leave this method empty because they don't need to do anything.
