### ISSUE TITLE
[Feature] vhus

### ISSUE THREAD

**Issue by yclzju** [thu-coai/ConvLab-2#68]
**Describe the feature**

I notice that the vhus in convlab2 only implement hus and vhus, without goal regularization. In the original paper, this part plays an important role. So I wonder will you implement this?
In fact, I try to finish this part as well, but I get puzzled about the function BOW, do you have any idea how to calculate this part? Especially BOW(Ut)

**Comment by truthless11** [comment]
@yclzju thanks for opening this issue. We're sorry that there is no plan for goal regularization since the details on implementation are unclear as you mentioned. We really appreciate it if you are working on this part.  The key point is to choose the dictionary for BOW.

**Comment by yclzju** [comment]
Yeah, and vhus's performance is worse than agenda based policy, there are only two simulators in convlab2, do you plan to add more simulators, especially whose performance can compete with agenda based policy.

**Comment by zqwerty** [comment]
We haven't find a better simulator on multiwoz yet.
