### ISSUE TITLE
[Feature] convlab-2 need to be improved in many aspects

### ISSUE THREAD

**Issue by wj-Mcat** [thu-coai/ConvLab-2#71]
**Describe the feature**
I think the `convlab-2` is a great toolkit for chinese student/developer to create fantastic chatbot. But after read the code, I find that there are many aspects to be improved in this project which should be in good project, eg: `auto-deploy-devops`, `auto-testing-deveops`, `full-document-in-code`, and so on ....

**Expected behavior**
I you agree, I will go ahead to improve the quality of this project which will be a good open-source project. I really like this project and field.

**Additional context**
I am a graduate student of `Beijing University of Posts and Telecommunications`, the author of open-source project [`python-wechaty`](https://github.com/wechaty/python-wechaty), and the  `[menter of  summer-of-code](https://github.com/wechaty/summer-of-code/issues/6)`. And more, my major interest directional is task-oriented dialogue.

**Comment by zqwerty** [comment]
Thanks! I appreciate it if you can help!
