### ISSUE TITLE
[Feature] Is there a way to create a light bot on my own few-shot dataset ?

### ISSUE THREAD

**Issue by wj-Mcat** [thu-coai/ConvLab-2#73]
**Describe the feature**
I have create a simple dataset for my own domain which contains little lines conversations sentences. And how can I create a simple bot on my own few-shot dataset like rasa ? 

**Expected behavior**
I hope this will be supported.

**Additional context**
And more, how to develop a new dataset for ConvLab-2 ? Is there a document for that ?

**Comment by wj-Mcat** [comment]
After read your code, I find that there are many hard-code for the specific domain. eg: 

- [book_taxi](https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/policy/rule/multiwoz/rule_based_multiwoz_bot.py#L144)
- [_update_greeting](https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/policy/rule/multiwoz/rule_based_multiwoz_bot.py#L130)
- [Type Mapping](https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/policy/vector/vector_multiwoz.py#L11)

If I need to develop a bot flow on a new dataset, it seems that I must write the `All of the Things` ?

**Comment by zqwerty** [comment]
> After read your code, I find that there are many hard-code for the specific domain. eg:
> 
> * [book_taxi](https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/policy/rule/multiwoz/rule_based_multiwoz_bot.py#L144)
> * [_update_greeting](https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/policy/rule/multiwoz/rule_based_multiwoz_bot.py#L130)
> * [Type Mapping](https://github.com/thu-coai/ConvLab-2/blob/master/convlab2/policy/vector/vector_multiwoz.py#L11)
> 
> If I need to develop a bot flow on a new dataset, it seems that I must write the `All of the Things` ?

These are part of the rule-based policy on **multiwoz** dataset. If you want to use your own dataset, you should write some code to modify every modules (NLU, DST, Policy, NLG, etc.). In your case, a simple rule policy may be enough.
