### ISSUE TITLE
[Maintenance] scoring metric

### ISSUE THREAD

**Issue by boliangz** [thu-coai/ConvLab-2#77]
Thanks for this great tool. I have a few questions about the scoring metric. 

The benchmark table uses "Complete rate", "Success rate", "Book rate", and "Inform P/R/F" as metrics. While in many recent papers, people use "Inform (%)", "Success (%)", "BLEU", and "Combined score" (a combined score of the previous three metrics with different weight). Can I assume "Success rate" = "Success (%)", "Inform F1" = "Inform (%)"? And it would be nice if you can add "BLEU" and "Combined score", just to align with others' work.

In the benchmark table, DAMB achieves 33.6 success rate, 57.4 inform F1, but in the original paper (https://arxiv.org/pdf/1911.10484.pdf), DAMB achieves 60.4 success (%), 76.3 inform (%). Why there is a huge difference?

**Comment by zqwerty** [comment]
We use different methods to calculate success rate. https://github.com/budzianowski/multiwoz evaluate "end2end" differently.

**Comment by huanli2012** [comment]
@zqwerty  I want to confirm that this is the final evaluation script for cross-lingual DST task, right? Only slots in `semi` are of interest, and slots in `book` are not. 
https://github.com/thu-coai/ConvLab-2/blob/50424c343574d9c14c63236da02cbd7bcc1af580/convlab2/dst/evaluate.py#L61
Thanks.

**Comment by zqwerty** [comment]
@huanli2012 slots in `book` will be included (#85) we are testing the model with all slots

**Comment by zqwerty** [comment]
#85 #122
