### ISSUE TITLE
Different frequency of domain after using same random seed

### ISSUE THREAD

**Issue by ShaneTian** [thu-coai/ConvLab-2#78]
I used `set_seed(20200202)` in `test_end2end.py`, but I got different frequency of domain. Why?

Can't random seeds fix user utterance?

**Comment by zqwerty** [comment]
Thanks! Please check this new simulator. I run `test_end2end.py` multiple times and get the same results.

**Comment by ShaneTian** [comment]
> Thanks! Please check this new simulator. I run `test_end2end.py` multiple times and get the same results.

OK!
If I used a fixed seed like `20200202`, which is right in end2end simulator?
1. Fixed user utterance whatever my response in multi-turn
2. Fixed first user utterance, maybe different user utterance according to different response of my model

**Comment by zqwerty** [comment]
> > Thanks! Please check this new simulator. I run `test_end2end.py` multiple times and get the same results.
> 
> OK!
> If I used a fixed seed like `20200202`, which is right in end2end simulator?
> 
> 1. Fixed user utterance whatever my response in multi-turn
> 2. Fixed first user utterance, maybe different user utterance according to different response of my model

2. Fixed first user utterance, maybe different user utterance according to different response of my model

**Comment by ShaneTian** [comment]
OK. Thanks
