### ISSUE TITLE
Shall we recognize the domains and slots in system utterances in Multi-domain Dialog State Tracking task?

### ISSUE THREAD

**Issue by huanli2012** [thu-coai/ConvLab-2#79]
Some slots such as restaurant_name may occur in system utterances, i.e. in dialogue MUL2499, the bot says, "All saints church looks good , would you like to head there ?". Logically there is no need to recognize slot values in system utterances but baseline models like SUMBT and TRADE did it. I want to confirm whether you will supply the annotations for system utterances in the final test set.

**Comment by zqwerty** [comment]
We will not provide dialog act annotation for cross-lingual DST. Only text is available. However, after the challenge, all annotations will be released
