### ISSUE TITLE
confirmation of the evaluation metric of cross-lingual DST task

### ISSUE THREAD

**Issue by huanli2012** [thu-coai/ConvLab-2#84]
I want to confirm whether this script is the final evaluation script of cross-lingual DST task. In this script, only slots in `semi` are of interest, and slots in `book` are not. 
https://github.com/thu-coai/ConvLab-2/blob/50424c343574d9c14c63236da02cbd7bcc1af580/convlab2/dst/evaluate.py#L61
Thanks.

**Comment by zqwerty** [comment]
slots in "book" will be included. We will update the script soon
