### ISSUE TITLE
[BUG] `final_goal_analyze` bug

### ISSUE THREAD

**Issue by ShaneTian** [thu-coai/ConvLab-2#92]
**Describe the bug**
The following case will be judged as a **mismatch** in `_final_goal_analyze`:
- case:
```
Constraints from final goal:
[('price', '75.10 pounds'), ('arriveBy', '15:45'), ('day', 'friday'), ('departure', 'cambridge'), ('destination', 'birmingham new street')]

self.booked[train]:
{'arriveBy': '07:44', 'day': 'friday', 'departure': 'cambridge', 'destination': 'birmingham new street', 'duration': '163 minutes', 'leaveAt': '05:01', 'price': '75.10 pounds', 'trainID': 'TR9678', 'Ref': '00002092'}
```

- code:
https://github.com/thu-coai/ConvLab-2/blob/db9ddd461048779f6d19fb2ffec7be3abb2b7465/convlab2/evaluator/multiwoz_eval.py#L390

**Expected behavior**
In `train` domain, `arriveBy` and `leaveAt` in goal may be not equal to item in DB exactly, but it is right.

**Comment by zqwerty** [comment]
Thanks! fixing

**Comment by zqwerty** [comment]
#99
