### ISSUE TITLE
I got a different results on test.

### ISSUE THREAD

**Issue by sookienlane** [thu-coai/ConvLab-2#93]
I run the test code. The result I got is far different from the result of yours.
For example, the result of **BERTNLU-RuleDST-RulePolicy-TemplateNLG** model is 

`complete number of dialogs/tot: 0.901    
success number of dialogs/tot: 0.571    
average precision: 0.7524100652627299  
average recall: 0.905928745583918  
average f1: 0.7967497596208643  
average book rate: 0.905176116838488  
average turn (succ): 10.325744308231174  
average turn (all): 12.374  
percentage of domains that satisfy the database constraints: 0.752  
percentage of dialogs that satisfy the database constraints: 0.617  
`
Is that normal?

**Comment by zqwerty** [comment]
we are now updating the evaluator. It will be more strict (check whether the entity appears in the database). When we finish, we will update the end2end result.
