### ISSUE TITLE
[Feature] Improve networks and memory implementations

### ISSUE THREAD

**Issue by brunonishimoto** [thu-coai/ConvLab-2#96]
**Describe the feature**
I think it would be a good idea to have more implementations of `policies`, `networks` and `memory` (all of this classes are implemented in `convlab2/policy/rlmodule.py`) such as `ReplayMemory`, `PrioritizedReplay`, `CNN`, etc. 
Most of these classes are implementend in [Convlab](https://github.com/ConvLab/ConvLab).

**Comment by zqwerty** [comment]
@truthless11 @liangrz15 How do you think?

**Comment by truthless11** [comment]
Thanks for opening this issue @brunonishimoto. [Convlab](https://github.com/ConvLab/ConvLab) transfers the code of policies and other models from [OpenAI Gym](https://github.com/openai/gym), while Convlab2 re-implements some of the policies for easier adaptation for developers. We are planning to implement DQN in the near future. We will appreciate it if you can help us implement more features on policies and memories.

**Comment by brunonishimoto** [comment]
Great! For sure, I am actually working on implementing a basic DQN algorithm.
For DQN algorithm to work, the action set needs to include combinations of actions in the dataset, like said  in #59 , right?

**Comment by truthless11** [comment]
> Great! For sure, I am actually working on implementing a basic DQN algorithm.
> For DQN algorithm to work, the action set needs to include combinations of actions in the dataset, like said in #59 , right?

Yes! Thanks for your help.
