### ISSUE TITLE
I think there has a problem in convlab2/evaluator/multiwoz_eval.py. 

### ISSUE THREAD

**Issue by kiseliu** [thu-coai/ConvLab-2#97]
I don't know why we count mismatch using the constraints of self.goal in line 376-384. 
self.goal isn't modified by other variables, it's still same with the initial goal.

**Comment by zqwerty** [comment]
We want to make sure that the entities we got from the system actually exist in the database:
1. 'reqt' in self.goal will be filled during the conversation according to the system agent replies. 
2. booked entities should be consistent with the domain information(info+reqt)

**Comment by kiseliu** [comment]
yes,of course. But you should use another goal variable, not self.goal. It's not updated.

**Comment by zqwerty** [comment]
> yes,of course. But you should use another goal variable, not self.goal. It's not updated.

We pass the reference of the goal to the evaluator. This goal will be updated in the user simulator
